spring:
  profiles:
    active: local


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
#    username: postgresql
#    password: postgrespassword
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

---

spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
    defer-datasource-initialization: true
    # 참조: https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
